### ISSUE TITLE
error

### ISSUE THREAD

**Issue by buthig666** [robinkarlberg/transfer.zip-web#3]
The transfer starts out strong and within seconds falls down to zero.  The client hangs there with no possible way to reinitiate the Dl.  The host side gives an error: OperationError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel send queue is full

Have tried with several devices both on and off lan and Wan.  I am a Pc builder and often times an open source beta tester but I know jackson about networking. 

Really wish I could get it to work.  It is exactly what I am looking for as the only other similar tool I can find is the Onionshare app and none of my friends and family even know what the Tor network even is.  (Also I feel bad gumming up the Tor network when I live in a free country and others lives actually depend on it... and it's slow as a broken clock)

**Comment by robinkarlberg** [comment]
Hi, thanks for taking the time and opening an issue!

After some experimentation I believe this is related to [this](https://stackoverflow.com/questions/32240191/webrtc-datachannel-buffered-full), where the data channel send queue size can reach a limit, in Chrome's case 16MB, and throw an error. I was able to reproduce the issue by using Chrome with a slower than normal internet connection. Firefox seems to have a larger queue size limit so I did not run into any problems there.

I have now added a check so that if the queue ever gets filled up, it waits a little before sending more data. Now the send queue should not be able to get too large. Don't hesitate to reach out if you still encounter any problems!

**Comment by buthig666** [comment]
Ok...  Still doesn't work (I am using updated Edge browser... so essentially chrome.)  I get the same results, which is unfortunate (possibly lasts a few moments longer.)  However I did find success using firefox for the host.  I am using Australian NBN 100 down 20 up...  (IRL it dips up and down around 15-20 for up but is consistent 100Mbs down)  I realize this isn't the best internet connection but would you consider this "slower than normal internet connection"??? 2 MB (Big B not little) up isn't too too bad...  What do I know I have Australian internet, regardless.... I wanted to give you any feedback that may help with development.

**Comment by robinkarlberg** [comment]
Hi, did you clear the browser cache for transfer.zip before trying again? You can refresh the cache easily by holding Shift while clicking the "refresh" button in the browser. Alternatively Shift+F5. I can't seem reproduce your error in Edge.

**Comment by buthig666** [comment]
Seems to work!  Good job, High five!

**Comment by robinkarlberg** [comment]
Great! 🙌

**Comment by buthig666** [comment]
I  love ur face
